import { RECIPES } from './Constants/ActionTypes';
const Types = {
    RECIPES_FETCH: 'RECIPES_FETCH',
    RECIPES_ADD: 'RECIPES_ADD',
    INGREDIENTS_ADD: 'INGREDIENTS_ADD',
    SUCCESS: RECIPES.SUCCESS,
    PENDING: RECIPES.PENDING,
    ERROR: RECIPES.ERROR,
}
export default Types; 