const Types = {
    ADD_RECIPE: 'ADD_RECIPE',
    FETCH_RECIPES_SUCCEESS: 'FETCH_RECIPES_SUCCEESS',
    FETCH_RECIPES_PENDING: 'FETCH_RECIPES_PENDING',
    FETCH_RECIPES_FAILURE: "FETCH_RECIPES_FAILURE",
    FETCH_RECIPES: 'FETCH_RECIPES',
    API: 'API'
}
export default Types; 